### ISSUE TITLE
Use a data license

### ISSUE THREAD

**Issue by nuest** [utfpr/NamingThePain#1]
Thanks for sharing the data behind your paper. I just want to point out the GPL the best license for data. GPL is made for software.

A Creative Commons license might be more suitable, ideally CC0, cf. https://www.openaire.eu/how-do-i-license-my-research-data and https://guides.nyu.edu/data_management/data-licensing

Even better would be a proper data license, such as ODbL or PDDL, see https://opendatacommons.org/licenses/index.html

**Comment by gustavopinto** [comment]
Hello @nuest, many thanks for opening this issue. I concur that GPL is not appropriated for non-software artifacts. I will take a look at these data licenses and discuss with @ipolato.

Gustavo

**Comment by ipolato** [comment]
Hi there! I completely agree with this. Our initial idea was to have some scripts/code here, but we ended up having only the raw data form our survey. We'll fix that! Thank you for the contribution!

Ivanilton

**Comment by ipolato** [comment]
We updated our license to the Open Data Commons Open Database License (ODbL). Once again, thanks!

Ivanilton
